name: FarmaEnvi
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts:
  footer: ^0.0.4
  provider: ^5.0.0
  http: ^0.13.3
  flutter_placeholder_textlines: ^1.2.0
  validators: ^3.0.0
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.4.2
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.2.1
  rxdart: ^0.27.7
  firebase_storage: ^11.1.2
  image_picker: ^0.8.7+4
  google_sign_in: ^6.1.0
  flutter_spinkit: ^5.2.0
  casa_vertical_stepper: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter 
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  floating_pullup_card: ^1.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/login.png
     - assets/images/menu.png
     - assets/images/avatar.png
     - assets/images/Delivery.png
     - assets/login/images/rectangle-14.png
     - assets/login/images/rectangle-10.png
     - assets/login/images/rectangle-65.png
     - assets/login/images/rectangle-31.png
     - assets/login/images/rectangle-7.png
     - assets/login/images/rectangle-61.png
     - assets/login/images/rectangle-30.png
     - assets/login/images/rectangle-67.png
     - assets/login/images/rectangle-66.png
     - assets/login/images/rectangle-23.png
     - assets/login/images/rectangle-33.png
     - assets/login/images/rectangle-61-JdH.png
     - assets/login/images/rectangle-29-xxj.png
     - assets/login/images/rectangle-57.png
     - assets/login/images/rectangle-17.png
     - assets/login/images/rectangle-26.png
     - assets/login/images/rectangle-16.png
     - assets/login/images/rectangle-19.png
     - assets/login/images/lista.png
     - assets/login/images/rectangle-27.png
     - assets/login/images/rectangle-39.png
     - assets/login/images/rectangle-38.png
     - assets/login/images/rectangle-41.png
     - assets/login/images/rectangle-12.png
     - assets/login/images/ellipse-1.png
     - assets/login/images/rectangle-29-wxX.png
     - assets/login/images/lista-cWF.png
     - assets/login/images/rectangle-17-zgT.png
     - assets/login/images/rectangle-28-RSB.png
     - assets/login/images/ellipse-3.png
     - assets/login/images/ellipse-5.png
     - assets/login/images/rectangle-13.png
     - assets/login/images/rectangle-64.png
     - assets/login/images/ellipse-4.png
     - assets/login/images/ellipse-2.png
     - assets/login/images/rectangle-40.png
     - assets/login/images/rectangle-31.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
