// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-L3kQmq11VrshC3lh1YL0tG1B201H_xU',
    appId: '1:848164697907:web:e9062abf906847f7797046',
    messagingSenderId: '848164697907',
    projectId: 'enviomedicamentos-4b853',
    authDomain: 'enviomedicamentos-4b853.firebaseapp.com',
    databaseURL: 'https://enviomedicamentos-4b853-default-rtdb.firebaseio.com',
    storageBucket: 'enviomedicamentos-4b853.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD41xl0QvEibdM4wqSEFBQpxGe6XSOPpCo',
    appId: '1:848164697907:android:d5905b9958bea0cf797046',
    messagingSenderId: '848164697907',
    projectId: 'enviomedicamentos-4b853',
    databaseURL: 'https://enviomedicamentos-4b853-default-rtdb.firebaseio.com',
    storageBucket: 'enviomedicamentos-4b853.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8v41h8k2fRD9dP4nsqKOhdyo3w1PRhIU',
    appId: '1:848164697907:ios:e0dd490393a7eedd797046',
    messagingSenderId: '848164697907',
    projectId: 'enviomedicamentos-4b853',
    databaseURL: 'https://enviomedicamentos-4b853-default-rtdb.firebaseio.com',
    storageBucket: 'enviomedicamentos-4b853.appspot.com',
    iosClientId: '848164697907-2g39ujjj4dr41mgn4k8gqji1v10vl84d.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8v41h8k2fRD9dP4nsqKOhdyo3w1PRhIU',
    appId: '1:848164697907:ios:e0dd490393a7eedd797046',
    messagingSenderId: '848164697907',
    projectId: 'enviomedicamentos-4b853',
    databaseURL: 'https://enviomedicamentos-4b853-default-rtdb.firebaseio.com',
    storageBucket: 'enviomedicamentos-4b853.appspot.com',
    iosClientId: '848164697907-2g39ujjj4dr41mgn4k8gqji1v10vl84d.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );
}
